language: node_js
node_js:
  - 10
sudo: false

branches:
  except:
    - gh-pages
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  fqdn: deck.dhanifudin.com
  on:
    branch: master
